language: java
jdk:
   - openjdk11

addons:
    sonarcloud:
        organization: leleuni
        token: 518b9b46c02e62434e54c9ea789cc8aca6bf929f

script:
    - ant build
    - sonar-scanner
